# MongoDB Connection Settings
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://sdikshaant:admin123@cluster0.3v4y4.mongodb.net/student_management_db?retryWrites=true&w=majority&appName=Cluster0}

# Application Port
server.port=8080
